# Generated by Django 5.0.7 on 2025-12-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="display_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
