# Generated by Django 5.0.7 on 2025-12-12 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="token",
            name="exam_type",
        ),
        migrations.RemoveField(
            model_name="token",
            name="status",
        ),
        migrations.RemoveField(
            model_name="token",
            name="uploaded_at",
        ),
        migrations.AddField(
            model_name="token",
            name="assigned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="token",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
