# Generated by Django 5.0.7 on 2025-12-15 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_reference"),
        ("tokens", "0002_remove_token_exam_type_remove_token_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="assigned",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.order",
            ),
        ),
    ]
