# Generated by Django 5.0.7 on 2025-12-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0003_alter_token_assigned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="assigned",
            field=models.BooleanField(default=False),
        ),
    ]
