# Generated by Django 5.0.7 on 2025-12-21 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Serviceproduct", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsappGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_class",
                    models.CharField(
                        choices=[("Science", "Science"), ("Art", "Art")], max_length=20
                    ),
                ),
                ("group_link", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Serviceproduct.serviceproduct",
                    ),
                ),
            ],
        ),
    ]
