# Generated by Django 5.0.7 on 2025-12-21 05:42

import django.db.models.deletion
import service_section.Whatsappgroup.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Serviceorder", "0001_initial"),
        ("Whatsappgroup", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsappgroup",
            name="student_class",
            field=models.CharField(
                choices=[("science", "Science"), ("art", "Art")], max_length=20
            ),
        ),
        migrations.CreateModel(
            name="WhatsAppAccessToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=service_section.Whatsappgroup.models.default_expiry_time
                    ),
                ),
                (
                    "joined_groups",
                    models.ManyToManyField(
                        blank=True, to="Whatsappgroup.whatsappgroup"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Serviceorder.serviceorder",
                    ),
                ),
            ],
        ),
    ]
