# Generated by Django 5.0.7 on 2025-12-12 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("product", "0001_initial"),
        ("tokens", "0002_remove_token_exam_type_remove_token_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="buyer_email",
        ),
        migrations.RemoveField(
            model_name="order",
            name="buyer_name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="buyer_phone",
        ),
        migrations.RemoveField(
            model_name="order",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="exam_type",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_reference",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_status",
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(default="PENDING", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name="AssignedToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tokens.token"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AssignedTokens",
        ),
    ]
