# Generated by Django 5.0.7 on 2025-12-14 09:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_order_buyer_email_remove_order_buyer_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reference",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
